/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2017-05-15 06:25:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.system;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class system_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t.display{display: none;}\r\n");
      out.write("\r\n");
      out.write("#systemRegisterArea {\r\n");
      out.write("\tmargin-left: 2%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css\">\r\n");
      out.write("<script src=\"/solar/static/lib/jquery-3.2.1.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"/solar/static/lib/jquery.serializeJSON.js\"></script>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/main/menu.jsp", out, false);
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t<!-- <div style=\"text-align:right;\">\r\n");
      out.write("\t\t<input type=\"button\" class=\"btn btn-default\" name=\"registerBtn\" value=\"등록\" disabled>\r\n");
      out.write("\t\t<input type=\"button\" class=\"btn btn-default\" name=\"clearBtn\" value=\"취소\">\r\n");
      out.write("\t\t<input type=\"button\" class=\"btn btn-default\" name=\"modifyBtn\" value=\"수정\" disabled>\r\n");
      out.write("\t\t<input type=\"button\" class=\"btn btn-default\" name=\"deleteBtn\" value=\"삭제\" disabled>\r\n");
      out.write("\t</div>\t\t -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"table-responsive\">\r\n");
      out.write("\t<table id=\"listTable\" class=\"table table-hover\">\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t\t\t<th>아이디</th>\r\n");
      out.write("\t\t\t<th>이름</th>\r\n");
      out.write("\t\t\t<th>설명</th>\r\n");
      out.write("\t\t\t<th>버전</th>\r\n");
      out.write("\t\t\t<th>전송 방식</th>\r\n");
      out.write("\t\t\t<th>타입</th>\r\n");
      out.write("\t\t\t<th>관리자</th>\r\n");
      out.write("\t\t\t<th>등록날짜</th>\r\n");
      out.write("\t\t</thead>\r\n");
      out.write("\t\t<tbody></tbody>\r\n");
      out.write("\t</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 수정폼  -->\r\n");
      out.write("<input type=\"button\" class=\"btn btn-default\" name=\"register\" value=\"시스템 등록\" style=\"margin-left: 90%;\"/>\r\n");
      out.write("<div id=\"systemInfoArea\" class=\"display\">\r\n");
      out.write("\t<form id=\"modifyForm\">\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"form-group col-md-5\">\r\n");
      out.write("  \t\t\t<label class=\"col-2 col-form-label\">ID</label>  \t\t\t\r\n");
      out.write("    \t\t<input class=\"form-control\" type=\"text\" id=\"example-text-input\" name=\"id\"> \t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group col-md-5\">\r\n");
      out.write(" \t\t\t <label class=\"col-2 col-form-label\">이름</label>\r\n");
      out.write("    \t\t <input class=\"form-control\" type=\"text\" id=\"example-search-input\" name=\"name\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group col-md-10\">\r\n");
      out.write("  \t\t\t<label class=\"col-2 col-form-label\">설명</label>\r\n");
      out.write("    \t\t<input class=\"form-control\" type=\"text\" id=\"example-email-input\" name=\"description\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group col-md-5\">\r\n");
      out.write("\t\t\t<label class=\"col-2 col-form-label\">버전</label>\r\n");
      out.write("    \t\t<input class=\"form-control\" type=\"text\" id=\"example-url-input\" name=\"version\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group col-md-5\">\r\n");
      out.write("\t\t \t<label class=\"col-2 col-form-label\">전송 방식</label>\r\n");
      out.write("\t\t\t<input class=\"form-control\" type=\"text\" id=\"example-tel-input\" name=\"transmission_type\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group col-md-5\">\r\n");
      out.write("\t\t\t<label class=\"col-2 col-form-label\">타입</label>\r\n");
      out.write("\t\t\t<input class=\"form-control\" type=\"text\"id=\"example-password-input\" name=\"type\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group col-md-5\">\r\n");
      out.write("  \t\t\t<label class=\"col-2 col-form-label\">관리자</label>\r\n");
      out.write("  \t\t\t<input class=\"form-control\" type=\"text\" id=\"example-password-input\" name=\"manager\">\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t<div class=\"form-group col-md-5\">\r\n");
      out.write("  \t\t\t<label class=\"col-2 col-form-label\">등록날짜</label>\r\n");
      out.write("  \t\t\t<input class=\"form-control\" type=\"text\" id=\"example-password-input\" name=\"regist_date\" readonly=\"readonly\">\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t<div class=\"form-group col-md-5\">\r\n");
      out.write("  \t\t\t<label class=\"col-2 col-form-label\">수정날짜</label>\r\n");
      out.write("  \t\t\t<input class=\"form-control\" type=\"text\" id=\"example-password-input\" name=\"up_Date\" readonly=\"readonly\"> \r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t<div class=\"form-group col-md-5\">\r\n");
      out.write("  \t\t\t<label class=\"col-2 col-form-label\">IP</label>\r\n");
      out.write("  \t\t\t<input class=\"form-control\" type=\"text\" id=\"example-password-input\" name=\"ip\" readonly=\"readonly\">\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t<div class=\"form-group col-md-12\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"unique_Id\" />\r\n");
      out.write("\t\t\t<input type=\"button\" class=\"btn btn-default\" name=\"modify\" value=\"수정\" style=\"margin-left:30%;\"/>\r\n");
      out.write("\t\t\t<input type=\"button\" class=\"btn btn-default\" name=\"delete\" value=\"삭제\" />\r\n");
      out.write("\t\t\t<input type=\"button\" class=\"btn btn-default\" name=\"close\" value=\"닫기\" />\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t</form>\t\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 등록폼  -->\r\n");
      out.write("\r\n");
      out.write("<div id=\"systemRegisterArea\" class=\"display\" class=\"form-group col-md-9\">\r\n");
      out.write("\t<form id=\"registerForm\">\r\n");
      out.write("\t\t<div class=\"form-group col-md-5\">\r\n");
      out.write("  \t\t\t<label class=\"col-2 col-form-label\">ID</label>  \t\t\t\r\n");
      out.write("    \t\t<input class=\"form-control\" type=\"text\" id=\"example-text-input\" name=\"id\"> \t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group col-md-5\">\r\n");
      out.write(" \t\t\t <label class=\"col-2 col-form-label\">이름</label>\r\n");
      out.write("    \t\t <input class=\"form-control\" type=\"text\" id=\"example-search-input\" name=\"name\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group col-md-10\">\r\n");
      out.write("  \t\t\t<label class=\"col-2 col-form-label\">설명</label>\r\n");
      out.write("    \t\t<input class=\"form-control\" type=\"text\" id=\"example-email-input\" name=\"description\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group col-md-5\">\r\n");
      out.write("\t\t\t<label class=\"col-2 col-form-label\">버전</label>\r\n");
      out.write("    \t\t<input class=\"form-control\" type=\"text\" id=\"example-url-input\" name=\"version\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group col-md-5\">\r\n");
      out.write("\t\t \t<label class=\"col-2 col-form-label\">전송 방식</label>\r\n");
      out.write("\t\t\t<input class=\"form-control\" type=\"text\" id=\"example-tel-input\" name=\"transmission_type\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group col-md-5\">\r\n");
      out.write("\t\t\t<label class=\"col-2 col-form-label\">타입</label>\r\n");
      out.write("\t\t\t<input class=\"form-control\" type=\"text\" id=\"example-password-input\" name=\"type\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group col-md-5\">\r\n");
      out.write("  \t\t\t<label class=\"col-2 col-form-label\">관리자</label>\r\n");
      out.write("  \t\t\t<input class=\"form-control\" type=\"text\" id=\"example-password-input\" name=\"manager\">\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t<div class=\"form-group col-md-12\">\r\n");
      out.write("  \t\t\t<input type=\"button\" class=\"btn btn-default\" name=\"register\" value=\"등록\" style=\"margin-left: 38%;\" />\r\n");
      out.write("\t\t\t<input type=\"button\" class=\"btn btn-default\" name=\"close\" value=\"닫기\" />\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\r\n");
      out.write("  </form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\t\r\n");
      out.write("\tgetSystemList();\r\n");
      out.write("\t\r\n");
      out.write("\t//아이디를 클릭 -> 시스템 수정\r\n");
      out.write("\t$(document).on('click', '#systemId', function(event){\r\n");
      out.write("\t\tevent.preventDefault();\r\n");
      out.write("\t\t$(\"#systemRegisterArea\").hide();\r\n");
      out.write("\t\tvar $id = $(this).text();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"GET\",\r\n");
      out.write("\t\t\turl:\"/solar/system/\"+$id,\r\n");
      out.write("\t\t\tsuccess:function(data,status,xhr){\r\n");
      out.write("\t\t\t\trenderSystemInfoView(data.system);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tasync: false,\r\n");
      out.write("\t\t\terror:function(xhr,status,error){\r\n");
      out.write("\t\t\t\tconsole.log(\"error : \"+xhr.status);\r\n");
      out.write("\t\t\t\talert(\"error : \"+xhr.status+\" 데이터를 불러오는 데 실패하였습니다.\");\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tcontentType:\"application/json\",\r\n");
      out.write("\t\t\tdataType:\"json\"\r\n");
      out.write("\t\t});\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//수정 버튼 클릭시 처리\r\n");
      out.write("\t$(document).on('click', \"#modifyForm  input[type='button'][name='modify']\", function(){\r\n");
      out.write("\t\tvar $json = JSON.stringify($('#modifyForm').serializeJSON());\t\t\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"PUT\",\r\n");
      out.write("\t\t\turl:\"/solar/system\",\r\n");
      out.write("\t\t\tdata:$json,\r\n");
      out.write("\t\t\tsuccess:function(data,status,xhr){\r\n");
      out.write("\t\t\t\trenderView(data.systemList);\r\n");
      out.write("\t\t\t\talert(\"수정되었습니다\");\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tasync: false,\r\n");
      out.write("\t\t\terror:function(xhr,status,error){\r\n");
      out.write("\t\t\t\tconsole.log(\"error : \"+xhr.status);\r\n");
      out.write("\t\t\t\talert(\"error : \"+xhr.status+\" 데이터를 수정 하는 데 실패하였습니다.\");\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tcontentType:\"application/json\",\r\n");
      out.write("\t\t\tdataType:\"json\"\r\n");
      out.write("\t\t});\t\t \r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//삭제 버튼 클릭시 삭제처리\r\n");
      out.write("\t$(document).on('click', \"#modifyForm  input[type='button'][name='delete']\", function(){\r\n");
      out.write("\t\tvar $json = JSON.stringify($('#modifyForm').serializeJSON());\r\n");
      out.write("\t\tconsole.log($json);\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"DELETE\",\r\n");
      out.write("\t\t\turl:\"/solar/system\",\r\n");
      out.write("\t\t\tdata:$json,\r\n");
      out.write("\t\t\tsuccess:function(data,status,xhr){\r\n");
      out.write("\t\t\t\t$(\"#systemInfoArea\").hide();\r\n");
      out.write("\t\t\t\trenderView(data.systemList);\r\n");
      out.write("\t\t\t\talert(\"삭제 되었습니다\");\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tasync: false,\r\n");
      out.write("\t\t\terror:function(xhr,status,error){\r\n");
      out.write("\t\t\t\tconsole.log(\"error : \"+xhr.status);\r\n");
      out.write("\t\t\t\talert(\"error : \"+xhr.status+\" 데이터를 삭제 하는 데 실패하였습니다.\");\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tcontentType:\"application/json\",\r\n");
      out.write("\t\t\tdataType:\"json\"\r\n");
      out.write("\t\t});\t\t \t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//등록 버튼 클릭시처리\r\n");
      out.write("\t$(document).on('click', \"input[type='button'][name='register']\", function(){\r\n");
      out.write("\t\t$(\"#systemInfoArea\").hide();\r\n");
      out.write("\t\t$(\"#systemRegisterArea\").show();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//시스템 뷰 에서  등록 버튼 클릭시 처리\r\n");
      out.write("\t$(document).on('click', \"#registerForm  input[type='button'][name='register']\", function(){\r\n");
      out.write("\t\tvar $json = JSON.stringify($('#registerForm').serializeJSON());\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"POST\",\r\n");
      out.write("\t\t\turl:\"/solar/system\",\r\n");
      out.write("\t\t\tdata:$json,\r\n");
      out.write("\t\t\tsuccess:function(data,status,xhr){\r\n");
      out.write("\t\t\t\t$(\"#systemRegisterArea\").hide();\r\n");
      out.write("\t\t\t\trenderView(data.systemList);\t\t\t\t\r\n");
      out.write("\t\t\t\talert(\"등록되었습니다.\");\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tasync: false,\r\n");
      out.write("\t\t\terror:function(xhr,status,error){\r\n");
      out.write("\t\t\t\tconsole.log(\"error : \"+xhr.status);\r\n");
      out.write("\t\t\t\talert(\"error : \"+xhr.status+\" 데이터를 등록 하는 데 실패하였습니다.\");\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tcontentType:\"application/json\",\r\n");
      out.write("\t\t\tdataType:\"json\"\r\n");
      out.write("\t\t});\t\t \r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//버튼 클릭시 처리\r\n");
      out.write("\t$(document).on('click', \"input[type='button'][name='close']\", function(){\r\n");
      out.write("\t\t$(\"#systemInfoArea\").hide();\r\n");
      out.write("\t\t$(\"#systemRegisterArea\").hide();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//system modify 값 넣기\r\n");
      out.write("\tfunction renderSystemInfoView(system){\r\n");
      out.write("\t\t$(\"#modifyForm input[name='id']\").val(system.id);\r\n");
      out.write("\t\t$(\"#modifyForm input[name='name']\").val(system.name);\r\n");
      out.write("\t\t$(\"#modifyForm input[name='description']\").val(system.description);\r\n");
      out.write("\t\t$(\"#modifyForm input[name='version']\").val(system.version);\r\n");
      out.write("\t\t$(\"#modifyForm input[name='transmission_type']\").val(system.transmission_type);\r\n");
      out.write("\t\t$(\"#modifyForm input[name='type']\").val(system.type);\r\n");
      out.write("\t\t$(\"#modifyForm input[name='manager']\").val(system.manager);\r\n");
      out.write("\t\t$(\"#modifyForm input[name='regist_date']\").val(system.regist_date);\r\n");
      out.write("\t\t$(\"#modifyForm input[name='up_Date']\").val(system.up_Date);\r\n");
      out.write("\t\t$(\"#modifyForm input[name='ip']\").val(system.ip);\r\n");
      out.write("\t\t$(\"#modifyForm input[name='unique_Id']\").val(system.unique_Id);\r\n");
      out.write("\t\t$(\"#systemInfoArea\").show();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//뷰를 불러오자 마자 ajax로 유저목록을 가져 온다\r\n");
      out.write("\tfunction getSystemList(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype:\"GET\",\r\n");
      out.write("\t\t\t\turl:\"/solar/system/systemList\",\r\n");
      out.write("\t\t\t\tsuccess:function(data,status,xhr){\r\n");
      out.write("\t\t\t\t\trenderView(data.systemList);\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tasync: false,\r\n");
      out.write("\t\t\t\terror:function(xhr,status,error){\r\n");
      out.write("\t\t\t\t\tconsole.log(\"error : \"+xhr.status);\r\n");
      out.write("\t\t\t\t\talert(\"error : \"+xhr.status+\" 데이터를 불러 오는 데 실패하였습니다.\");\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tcontentType:\"application/json\",\r\n");
      out.write("\t\t\t\tdataType:\"json\"\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//systemList\r\n");
      out.write("\tfunction renderView(data){\r\n");
      out.write("\t\t$(\"#listTable > tbody\").empty();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t$(data).each(function(){\r\n");
      out.write("\t\t\tvar $tr = $(\"<tr/>\").appendTo(\"#listTable\");\r\n");
      out.write("\t\t\tvar $td = $(\"<td/>\").appendTo($tr);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar $a = $(\"<a/>\",{\"href\":\"#\",\"id\":\"systemId\"}).appendTo($td);\t\t\t\r\n");
      out.write("\t\t\t$($a).text(this.id);\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$td = $(\"<td/>\").appendTo($tr);\r\n");
      out.write("\t\t\t$($td).text(this.name);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$td = $(\"<td/>\").appendTo($tr);\r\n");
      out.write("\t\t\t$($td).text(this.description);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$td = $(\"<td/>\").appendTo($tr);\r\n");
      out.write("\t\t\t$($td).text(this.version);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$td = $(\"<td/>\").appendTo($tr);\r\n");
      out.write("\t\t\t$($td).text(this.transmission_type);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$td = $(\"<td/>\").appendTo($tr);\r\n");
      out.write("\t\t\t$($td).text(this.type);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$td = $(\"<td/>\").appendTo($tr);\r\n");
      out.write("\t\t\t$($td).text(this.manager);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$td = $(\"<td/>\").appendTo($tr);\r\n");
      out.write("\t\t\t$($td).text(this.regist_date);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$td = $(\"<td/>\").appendTo($tr);\r\n");
      out.write("\t\t\t$(\"<input/>\",{\"type\":\"hidden\",\"value\":this.unique_Id}).appendTo($td);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
