/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2017-05-15 06:24:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.interface_;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class interface_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/solar/static/css/bootstrap.min.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/solar/static/css/bootstrap-theme.min.css\"/>\r\n");
      out.write("<script src=\"/solar/static/css/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"/solar/static/lib/jquery-3.2.1.js\"></script>\r\n");
      out.write("<script src=\"/solar/static/lib/jquery.serializeJSON.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<title>인터페이스</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/main/menu.jsp", out, false);
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t<div style=\"text-align:right;\">\r\n");
      out.write("\t\t<input type=\"button\" class=\"btn btn-default\" name=\"registerBtn\" value=\"등록\">\r\n");
      out.write("\t\t<input type=\"button\" class=\"btn btn-default\" name=\"clearBtn\" value=\"취소\">\r\n");
      out.write("\t\t<input type=\"button\" class=\"btn btn-default\" name=\"modifyBtn\" value=\"수정\" disabled>\r\n");
      out.write("\t\t<input type=\"button\" class=\"btn btn-default\" name=\"deleteBtn\" value=\"삭제\" disabled>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"table-responsive\">\r\n");
      out.write("\t<table class=\"table table-hover\" id=\"interfaceList\">\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>아이디</th>\r\n");
      out.write("\t\t\t\t<th>이름</th>\r\n");
      out.write("\t\t\t\t<th>버전</th>\r\n");
      out.write("\t\t\t\t<th>타입</th>\r\n");
      out.write("\t\t\t\t<th>담당자</th>\r\n");
      out.write("\t\t\t\t<th>수정날짜</th>\r\n");
      out.write("\t\t\t\t<th></th>\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</thead>\r\n");
      out.write("\t\t<tbody></tbody>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<hr/>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t<form id=\"interfaceForm\" class=\"hide\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"uniqueId\">\r\n");
      out.write("\t\t<div class=\"form-group col-md-9\">\r\n");
      out.write("\t\t\t<label>아이디</label>\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" name=\"id\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group col-md-3\">\r\n");
      out.write("\t\t\t<label>버전</label>\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" name=\"version\"/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group col-md-6\">\r\n");
      out.write("\t\t\t<label>이름</label>\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" name=\"name\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group col-md-6\">\r\n");
      out.write("\t\t\t<label>담당자</label>\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" name=\"manager\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group col-md-9\">\r\n");
      out.write("\t\t\t<label>설명</label>\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" name=\"description\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group col-md-3\">\r\n");
      out.write("\t\t\t<label>타입</label>\r\n");
      out.write("\t\t\t<select class=\"form-control\" name=\"type\">\r\n");
      out.write("\t\t\t\t<option value=\"BAT\">BAT</option>\r\n");
      out.write("\t\t\t\t<option value=\"DFD\">DFD</option>\r\n");
      out.write("\t\t\t\t<option value=\"ONL\">ONL</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group col-md-4\">\r\n");
      out.write("\t\t\t<label>수신시스템ID</label>\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" name=\"srcSystemId\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group col-md-4\">\r\n");
      out.write("\t\t\t<label>수신시스템 전송방식</label>\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" name=\"srcSystemType\" readonly>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group col-md-4\">\r\n");
      out.write("\t\t\t<label>수신시스템 담당자</label>\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" name=\"srcSystemManager\" readonly>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group col-md-4\">\r\n");
      out.write("\t\t\t<label>송신시스템ID</label>\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" name=\"tgtSystemId\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group col-md-4\">\r\n");
      out.write("\t\t\t<label>송신시스템 전송방식</label>\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" name=\"tgtSystemType\" readonly>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group col-md-4\">\r\n");
      out.write("\t\t\t<label>송신시스템 담당자</label>\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" name=\"tgtSystemManager\" readonly>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group col-md-6\">\r\n");
      out.write("\t\t\t<label>ip</label>\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" name=\"ip\" readonly>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group col-md-3\">\r\n");
      out.write("\t\t\t<label>등록날짜</label>\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" name=\"registDate\" readonly>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"form-group col-md-3\">\r\n");
      out.write("\t\t\t<label>수정날짜</label>\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" name=\"upDate\" readonly>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\t\r\n");
      out.write("\tgetInterfaceList();\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"input[name='registerBtn']\").click(function(){\r\n");
      out.write("\t\tif($(\"#interfaceForm\").attr('class')==\"hide\"){\r\n");
      out.write("\t\t\t$(\"#interfaceForm\").attr('class',\"show\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif($(\"#interfaceForm\").attr('class')==\"show\"){\r\n");
      out.write("\t\t\tif($(\"input[name='modifyBtn']\").attr(\"disabled\")!=\"disabled\"){\r\n");
      out.write("\t\t\t\tclearInfo();\r\n");
      out.write("\t\t\t\t$(\"input[name='modifyBtn'], input[name='deleteBtn']\").attr(\"disabled\",true);\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(checkForm()==false){\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tvar $json = JSON.stringify($('#interfaceForm').serializeJSON());\r\n");
      out.write("\t\t\tconsole.log($json);\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype:\"POST\",\r\n");
      out.write("\t\t\t\turl:\"/solar/interface\",\r\n");
      out.write("\t\t\t\tdata:$json,\r\n");
      out.write("\t\t\t\tsuccess:function(data,status,xhr){\r\n");
      out.write("\t\t\t\t\tlocation.href=\"/solar/interface\";\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror:function(xhr,status,error){\r\n");
      out.write("\t\t\t\t\talert(\"error\"+xhr.status);\t\t\t\t\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tasync: false,\r\n");
      out.write("\t\t\t\tcontentType:\"application/json\"\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"input[name='clearBtn']\").click(function(){\r\n");
      out.write("\t\tclearInfo();\r\n");
      out.write("\t\t$(\"input[name='modifyBtn'], input[name='deleteBtn']\").attr(\"disabled\",true);\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".getInfo\").on(\"click\",function(){\r\n");
      out.write("\t\t$(\"#interfaceForm\").attr('class',\"show\");\r\n");
      out.write("\t\t$(\"input[name='modifyBtn'], input[name='deleteBtn']\").attr(\"disabled\",false);\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"GET\",\r\n");
      out.write("\t\t\turl:\"/solar/interface/\"+$(this).attr(\"u-id\"),\r\n");
      out.write("\t\t\tsuccess:function(data,status,xhr){\r\n");
      out.write("\t\t\t\tinterfaceInfo(data.interFace);\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror:function(xhr,status,error){\r\n");
      out.write("\t\t\t\talert(\"error\"+xhr.status);\t\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tasync: false,\r\n");
      out.write("\t\t\tcontentType:\"application/json\",\r\n");
      out.write("\t\t\tdataType:\"json\"\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"input[name='modifyBtn']\").on(\"click\",function(){\r\n");
      out.write("\t\tif(checkForm()==false){\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar $json = JSON.stringify($('#interfaceForm').serializeJSON());\r\n");
      out.write("\t\tconsole.log($json);\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"PUT\",\r\n");
      out.write("\t\t\turl:\"/solar/interface\",\r\n");
      out.write("\t\t\tdata:$json,\r\n");
      out.write("\t\t\tsuccess:function(data,status,xhr){\r\n");
      out.write("\t\t\t\tlocation.href=\"/solar/interface\";\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror:function(xhr,status,error){\r\n");
      out.write("\t\t\t\talert(\"error\"+xhr.status);\t\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tasync: false,\r\n");
      out.write("\t\t\tcontentType:\"application/json\"\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"input[name='deleteBtn']\").on(\"click\",function(){\r\n");
      out.write("\t\tvar $json = JSON.stringify($('#interfaceForm').serializeJSON());\r\n");
      out.write("\t\tconsole.log($json);\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"DELETE\",\r\n");
      out.write("\t\t\turl:\"/solar/interface\",\r\n");
      out.write("\t\t\tdata:$json,\r\n");
      out.write("\t\t\tsuccess:function(data,status,xhr){\r\n");
      out.write("\t\t\t\tlocation.href=\"/solar/interface\";\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror:function(xhr,status,error){\r\n");
      out.write("\t\t\t\talert(\"error\"+xhr.status);\t\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tasync: false,\r\n");
      out.write("\t\t\tcontentType:\"application/json\"\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\t\r\n");
      out.write("\r\n");
      out.write("\tfunction getInterfaceList(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype:\"GET\",\r\n");
      out.write("\t\t\t\turl:\"/solar/interface/list\",\r\n");
      out.write("\t\t\t\tsuccess:function(data,status,xhr){\r\n");
      out.write("\t\t\t\t\trenderView(data.interfaceList);\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tasync: false,\r\n");
      out.write("\t\t\t\terror:function(xhr,status,error){\r\n");
      out.write("\t\t\t\t\tconsole.log(\"error : \"+xhr.status);\r\n");
      out.write("\t\t\t\t\talert(\"error : \"+xhr.status);\r\n");
      out.write("\t\t\t\t\talert(\"데이터를 불러오는 데 실패하였습니다.\")\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tcontentType:\"application/json\",\r\n");
      out.write("\t\t\t\tdataType:\"json\"\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction renderView(data){\r\n");
      out.write("\t\t$(data).each(function(){\r\n");
      out.write("\t\t\tvar $tr = $(\"<tr/>\",{\r\n");
      out.write("\t\t\t\t\"class\":\"getInfo\",\r\n");
      out.write("\t\t\t\t\"u-id\":this.uniqueId,\r\n");
      out.write("\t\t\t}).appendTo(\"#interfaceList tbody\");\r\n");
      out.write("\t\t\tvar $td = $(\"<td/>\").appendTo($tr);\r\n");
      out.write("\t\t\t$($td).text(this.id);\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$td = $(\"<td/>\").appendTo($tr);\r\n");
      out.write("\t\t\t$($td).text(this.name);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$td = $(\"<td/>\").appendTo($tr);\r\n");
      out.write("\t\t\t$($td).text(this.version);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$td = $(\"<td/>\").appendTo($tr);\r\n");
      out.write("\t\t\t$($td).text(this.type);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$td = $(\"<td/>\").appendTo($tr);\r\n");
      out.write("\t\t\t$($td).text(this.manager);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$td = $(\"<td/>\").appendTo($tr);\r\n");
      out.write("\t\t\t$($td).text(this.upDate);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$td = $(\"<td/>\").appendTo($tr);\r\n");
      out.write("\t\t\t$btn = $(\"<input/>\",{\r\n");
      out.write("\t\t\t\t'type':\"button\",\r\n");
      out.write("\t\t\t\t'class':\"btn btn-default\",\r\n");
      out.write("\t\t\t\t'onclick':\"location.href='/solar/interface/delete/\"+this.uniqueId+\"'\",\r\n");
      out.write("\t\t\t\t'value':\"삭제\"}).appendTo($td);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction interfaceInfo(interFace){\r\n");
      out.write("\t\t$(\"#interfaceForm input[name='id']\").val(interFace.id);\r\n");
      out.write("\t\t$(\"#interfaceForm input[name='version']\").val(interFace.version);\r\n");
      out.write("\t\t$(\"#interfaceForm input[name='name']\").val(interFace.name);\r\n");
      out.write("\t\t$(\"#interfaceForm input[name='description']\").val(interFace.description);\r\n");
      out.write("\t\t$(\"#interfaceForm select[name='type']\").val(interFace.type);\r\n");
      out.write("\t\t$(\"#interfaceForm input[name='manager']\").val(interFace.manager);\r\n");
      out.write("\t\t$(\"#interfaceForm input[name='srcSystemId']\").val(interFace.srcSystemId);\r\n");
      out.write("\t\t$(\"#interfaceForm input[name='srcSystemType']\").val(interFace.srcSystemType);\r\n");
      out.write("\t\t$(\"#interfaceForm input[name='srcSystemManager']\").val(interFace.srcSystemManager);\r\n");
      out.write("\t\t$(\"#interfaceForm input[name='tgtSystemId']\").val(interFace.tgtSystemId);\r\n");
      out.write("\t\t$(\"#interfaceForm input[name='tgtSystemType']\").val(interFace.tgtSystemType);\r\n");
      out.write("\t\t$(\"#interfaceForm input[name='tgtSystemManager']\").val(interFace.tgtSystemManager);\r\n");
      out.write("\t\t$(\"#interfaceForm input[name='ip']\").val(interFace.ip);\r\n");
      out.write("\t\t$(\"#interfaceForm input[name='registDate']\").val(interFace.registDate);\r\n");
      out.write("\t\t$(\"#interfaceForm input[name='upDate']\").val(interFace.upDate);\r\n");
      out.write("\t\t$(\"#interfaceForm input[name='uniqueId']\").val(interFace.uniqueId);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction clearInfo(){\r\n");
      out.write("\t\t$(\"#interfaceForm input[name='id']\").val('');\r\n");
      out.write("\t\t$(\"#interfaceForm input[name='version']\").val('');\r\n");
      out.write("\t\t$(\"#interfaceForm input[name='name']\").val('');\r\n");
      out.write("\t\t$(\"#interfaceForm input[name='description']\").val('');\r\n");
      out.write("\t\t$(\"#interfaceForm select[name='type']\").val('BAT');\r\n");
      out.write("\t\t$(\"#interfaceForm input[name='manager']\").val('');\r\n");
      out.write("\t\t$(\"#interfaceForm input[name='srcSystemId']\").val('');\r\n");
      out.write("\t\t$(\"#interfaceForm input[name='srcSystemType']\").val('');\r\n");
      out.write("\t\t$(\"#interfaceForm input[name='srcSystemManager']\").val('');\r\n");
      out.write("\t\t$(\"#interfaceForm input[name='tgtSystemId']\").val('');\r\n");
      out.write("\t\t$(\"#interfaceForm input[name='tgtSystemType']\").val('');\r\n");
      out.write("\t\t$(\"#interfaceForm input[name='tgtSystemManager']\").val('');\r\n");
      out.write("\t\t$(\"#interfaceForm input[name='ip']\").val('');\r\n");
      out.write("\t\t$(\"#interfaceForm input[name='registDate']\").val('');\r\n");
      out.write("\t\t$(\"#interfaceForm input[name='upDate']\").val('');\r\n");
      out.write("\t\t$(\"#interfaceForm input[name='uniqueId']\").val('');\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction checkForm(){\r\n");
      out.write("\t\tif($(\"input[name='id']\").val()==''){\r\n");
      out.write("\t\t\talert(\"아이디를 입력하세요\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif($(\"input[name='name']\").val()==''){\r\n");
      out.write("\t\t\talert(\"이름을 입력하세요\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif($(\"input[name='manager']\").val()==''){\r\n");
      out.write("\t\t\talert(\"담당자를 선택하세요\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif($(\"input[name='srcSystemId']\").val()==''){\r\n");
      out.write("\t\t\talert(\"수신시스템을 선택하세요\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif($(\"input[name='tgtSystemId']\").val()==''){\r\n");
      out.write("\t\t\talert(\"송신시스템을 선택하세요\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
